package com.husseinabdallah287.springdatajparelationships.models;

public enum MIDDLEWARENAME {
	AVENUE, MATER, NAIROBIHOSPITAL, GETRUDES, MPSHAH, METROPOLITAN, AGAKHANKISUMU, AGAKHANMOMBASA,
	AGAKHANNAIROBI, NONE

}
